[build-system]
requires = ["meson-python"]
build-backend = "mesonpy"

[project]
name = "misdesigner"
version = "0.0.1"
description = "Tool for designing and simulating multi-slit imaging spectrographs"
requires-python = ">=3.8"
authors = [
  { name = "Sunip K. Mukherjee", email = "sunipkmukherjee@gmail.com" },
  { name = "Charmi Patel", email = "charmi_patel2@student.uml.edu" },
]
dependencies = [
  'numpy>=1.20.0',
  'tqdm>=4.60.0',
  'xarray',
  'natsort',
  'netcdf4',
  'dataclasses_json',
  'scikit-image',
]
